name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn

    - name: Cypress component tests
      run: |
        ls -l
        npx cypress run --component
